eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
  cloud:
    compatibility-verifier:
      enabled: false
#短路器设置
feign:
  hystrix:
    enabled: true