server:
  port: 8881
spring:
  application:
    name: config-client
  rabbitmq:
     host: localhost
     port: 5672
#     username:
#     password:
  cloud:
    config:
      label: master
      profile: dev
      discovery:
#        是从配置中心读取文件。
        enabled: true
#        配置中心的servieId，即服务名。
      serviceId: config-server

#      搭建高可用配置中心,此处需要注释掉
#      uri: http://localhost:8888/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

