server:
  port: 8888
spring:
  application:
    name: config-server
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quliang123/SpringcloudConfig/
          searchPaths: respo
          username: 529075990@qq.com
          password: quliang520
          label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh